declare module '@riophae/vue-treeselect'
declare module '@vue-composent/vue-xuploader'
declare module '@riophae/vue-treeselect'
declare module 'contrast-color'
declare module 'vue-monoplasty-slide-verify'
declare module 'vue-awesome-swiper'
declare module 'join-path'
